### ISSUE TITLE
how to make the circle thicker 

### ISSUE THREAD

**Issue by fas3r** [trungk18/jquery-loading#2]
Hello,

Is there a way to make the border of the circle thicker / larger ? 

Thanks.

**Comment by trungvose** [comment]
Current there is no support that you can set it up when initiating a new loading. But If you want to apply to all the loading, let override the CSS

Refer to [jquery-loading.css](https://github.com/trungk18/jquery-loading/blob/master/css/jquery-loading.css)

This is by default with 3px border. You can increase it to match your need. For example 5px or even 10px.
 
```css
.js-loading-indicator { //the green one
  border: 3px solid transparent;
 }

.js-loading-indicator.double::before { // the red one
  border: 3px solid transparent;
}

.js-loading-indicator.triple::before, .js-loading-indicator.triple::after { //the yellow one
  border: 3px solid transparent; }
```
